Fix wrong documentation url
ishiDACo/vulsrepo pull request #159
Opened 2020-11-10 18:17 UTC by Jiab77

The current documentation url is still the one from the previous repo.

2020-11-10 18:18 UTC, Jiab77 commented
@ishiDACo Could you please review this pull request when you have time? 👍🏼

2020-11-10 18:26 UTC, Jiab77 commented
@ishiDACo I'm just wondering if that would not be better to point to the documentation you've recently updated?

Like: https://vuls.io/docs/en/vulsrepo.html

2020-11-11 03:01 UTC, ishiDACo requested changes
https://vuls.io/docs/en/vulsrepo.html is preferable.

2020-11-11 10:54 UTC, Jiab77 commented
@ishiDACo Thanks a lot for your advice, I'll then change the pull request.

2020-11-11 10:56 UTC, Jiab77 commented
Changed done :)

2020-11-11 12:48 UTC, ishiDACo approved these changes
Thank you very much!

2020-11-11 12:48 UTC, merged